# Generated by Django 4.2 on 2024-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=5000)),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['-timestamp_field'],
            },
        ),
    ]
