# Generated by Django 5.0.1 on 2024-01-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketingregister',
            table='marketing_register',
        ),
    ]
