# Generated by Django 5.0.1 on 2024-01-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketingregister_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketingregister',
            table='Marketing_register',
        ),
    ]
