"""
Django settings for cinystore project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from . info import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)j1sx$(*kmwd_svhyy85_c#3*@zp%y*wc!7v6a1+%8828mvbb@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1','localhost']



AUTH_USER_MODEL = "cinystoreapp.User" 


# Application definition

INSTALLED_APPS = [
    'cinystoreapp',
    'corporate',
    'channels',
    'phonenumber_field',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'widget_tweaks',
    'storages',
    'django_s3_storage',
    'rest_framework',
    'captcha',
    'podadmin',
    'superadmin',
    'business',
    'labels',
    'marketing',
    'keepitshort',
    'base',
    
]
SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cinystore.urls'

CSRF_TRUSTED_ORIGINS = ['https://www.cinystore.com','https://cinystore.com']
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    'https://cinystore.com',
    'https://www.cinystore.com',
    'https://3.109.48.139',
]
CSRF_COOKIE_SECURE = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cinystore.wsgi.application'
ASGI_APPLICATION = 'cinystore.asgi.application'



RECAPTCHA_PUBLIC_KEY = '6LdzFvwoAAAAAJsT3AGS4TazKX55K9S0HFAij9Sv'
RECAPTCHA_PRIVATE_KEY = '6LdzFvwoAAAAAFbrWHqpgkYvbgtVgNwHDSu1gVn6'


'''
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
'''


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cinystore',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cinystore',
#         'USER': 'myuser',
#         'PASSWORD': 'cinystore',
#         'HOST': '3.109.48.139',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT
EMAIL_USE_SSL = True  # or True if your server requires SSL
EMAIL_DEBUG = True  # Enable debugging




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
#PRODUCERLOGINPAGE_URL = '/Producerloginpage/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#PRODUCERLOGINPAGE_ROOT = os.path.join(BASE_DIR, 'Producerloginpage')

# # AWS S3 Configuration
# AWS_QUERYSTRING_AUTH = False
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_ACCESS_KEY_ID = 'AKIASEKFWL2BAIAHRLQP'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'cinystorepage'
# AWS_STORAGE_LINK = 'https://cinystorepage.s3.amazonaws.com/'
# # TMDB_LINK = 'https://image.tmdb.org/t/p/w500'
# # AWS_S3_REGION_NAME = 'ap-south-1'


# AWS S3 Configuration
AWS_QUERYSTRING_AUTH = False
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'AKIASEKFWL2BAIAHRLQP'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'demo-test-bucket-cinystore'



OTPLESS_CLIENT_ID = "AOS26987R093U7ESDGNIBOQIXBMAIRI8"
OTPLESS_KEY = "jyc57isaghnpmxh1snuq8mvngu32m1qe"


SITE_URL ='www.cinystore.com'

#confirmation_link = f'{settings.SITE_URL}/activate/{activation_key}'

#MSG91 
MSG91_AUTH_KEY = '412276AiWQwTv6v6586caa4P1'