# Generated by Django 4.2 on 2024-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abusereport',
                'ordering': ['timestamp_field'],
            },
        ),
    ]
