# Generated by Django 5.0.1 on 2024-01-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencyregister',
            table='agencyregister',
        ),
        migrations.AlterModelTable(
            name='corporateregister',
            table='corporateregister',
        ),
        migrations.AlterModelTable(
            name='individualregister',
            table='individualregister',
        ),
        migrations.AlterModelTable(
            name='ottregister',
            table='ottregister',
        ),
    ]
