# Generated by Django 5.0.1 on 2024-01-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_agencyregister_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyregister',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='agencyregister',
            name='twitter_account',
        ),
        migrations.RemoveField(
            model_name='corporateregister',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='corporateregister',
            name='twitter_account',
        ),
        migrations.RemoveField(
            model_name='individualregister',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='individualregister',
            name='twitter_account',
        ),
        migrations.RemoveField(
            model_name='ottregister',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='ottregister',
            name='twitter_account',
        ),
    ]
