# Generated by Django 4.2 on 2024-01-20 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import podadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinystoreapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('Movie_name', models.CharField(max_length=100)),
                ('Video', models.FileField(null=True, upload_to=podadmin.models.path_rename_video, verbose_name='')),
                ('Image', models.ImageField(blank=True, upload_to='Posters/')),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(default='mydata2', max_length=100)),
                ('like_count', models.BigIntegerField(blank=True, default=False, null=True)),
                ('comment_count', models.BigIntegerField(blank=True, default=False, null=True)),
                ('share_count', models.BigIntegerField(blank=True, default=False, null=True)),
                ('source', models.CharField(blank=True, default='Cinystore News Network', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, default='Users/blank_profile.webp', max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Clips',
                'ordering': ['-timestamp_field'],
            },
        ),
        migrations.CreateModel(
            name='PodAdmin',
            fields=[
                ('pod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pod_name', models.CharField(max_length=100)),
                ('pod_email', models.EmailField(max_length=100)),
                ('pod_phone', models.CharField(max_length=100)),
                ('pod_created_at', models.DateTimeField(auto_now_add=True)),
                ('pod_is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'podadmin',
            },
        ),
        migrations.CreateModel(
            name='PostText1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
                ('Image', models.ImageField(blank=True, upload_to=podadmin.models.path_and_rename_post)),
                ('Heading', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(default='mydata3', max_length=100)),
                ('like_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('comment_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('share_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('source', models.CharField(blank=True, default='Cinystore News Network', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, default='Users/blank_profile.webp', max_length=255, null=True)),
                ('slug', models.SlugField(default=0)),
            ],
            options={
                'db_table': 'PostText',
                'ordering': ['-timestamp_field'],
            },
        ),
        migrations.CreateModel(
            name='CreateLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Production_house', models.CharField(max_length=50)),
                ('Producer', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=250)),
                ('Director', models.CharField(max_length=100)),
                ('Music_director', models.CharField(max_length=100)),
                ('Poster', models.ImageField(blank=True, upload_to=podadmin.models.path_and_rename)),
                ('Banner', models.ImageField(blank=True, upload_to=podadmin.models.path_and_rename)),
                ('Release_date', models.DateField(max_length=100)),
                ('synopsis', models.CharField(max_length=2000)),
                ('trailer', models.CharField(max_length=255)),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(default='mydata', max_length=100)),
                ('Url_name', models.CharField(default=None, max_length=100, null=True)),
                ('Other_Languages', models.CharField(max_length=100, null=True)),
                ('lyricist', models.CharField(max_length=100, null=True)),
                ('choreographer', models.CharField(max_length=100, null=True)),
                ('Script_writer', models.CharField(max_length=100, null=True)),
                ('Running_Time', models.CharField(max_length=100, null=True)),
                ('Maturity', models.CharField(max_length=100, null=True)),
                ('Budget', models.CharField(max_length=100, null=True)),
                ('Distribution', models.CharField(max_length=100, null=True)),
                ('Recording_studio', models.CharField(max_length=100, null=True)),
                ('Graphic_designer', models.CharField(max_length=100, null=True)),
                ('like_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('follow_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('share_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('comment_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('Singers', models.CharField(max_length=100, null=True)),
                ('Editor', models.CharField(max_length=100, null=True)),
                ('Cinematographer', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(blank=True, default='Cinystore News Network', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, default='User/blank_profile.webp', max_length=255, null=True)),
                ('producer_id', models.ForeignKey(db_column='producer_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cinystoreapp.producerregister', verbose_name='producer_register')),
            ],
            options={
                'db_table': 'Create_label',
                'ordering': ['-timestamp_field'],
            },
        ),
    ]
