# Generated by Django 4.2 on 2023-10-18 13:40

import cinystoreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinystoreapp', '0004_posttext1_production_house_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profilephoto',
            field=models.ImageField(default='Users/blank_profile.webp', null=True, upload_to=cinystoreapp.models.rename),
        ),
    ]
